# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# SSH
# Run shell commands or a script on a remote machine using SSH
- task: SSH@0
  inputs:
    sshEndpoint: mohas
    runOptions: 'commands'
    commands: pwd; hostname; touch /home/azureuser/mohaa/mohaafile1; cp /home/azureuser/mohaa/* /home/azureuser/mohaa1 
    #scriptPath: # Required when runOptions == Script
    #inline: # Required when runOptions == Inline
    #interpreterCommand: # Used when runOptions == Inline
    #args: # Optional
    #failOnStdErr: true # Optional 
