# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#parameters:
#- name: storage_account_name # name of the parameter; required
  #type: string # data type of the parameter; required
  
  
trigger: 
- release
- dev

pool:
  vmImage: ubuntu-latest

variables:
- template: parameters.yml

steps:
- script: echo $(${{ variables.storage_account_name }})
  displayName: 'Run a one-line script'

#- script: |
 #   ls
 #   echo Add other tasks to build, test, and deploy your project.
 #   echo See https://aka.ms/yaml
 # displayName: 'Run a multi-line script'
