# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- task: ManualValidation@0
  inputs:
    notifyUsers: 'mohasinpathan005@gmail.com'
    instructions: 'Please approve'

- task: ManualIntervention@8
  inputs:
    instructions: 'Please approve'
    emailRecipients: 'mohasinpathan005@gmail.com'
- task: AzureCLI@2
  inputs:
      azureSubscription: 'Pay-As-You-Go (40783f5c-2558-41a9-a5af-97b47669376e)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
      
      
      
           az storage blob exists -c testcontainer -n sample.txt --account-name newstrac1 --sas-token ?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-04-29T15:11:33Z&st=2022-04-21T07:11:33Z&spr=https&sig=CTLTUh7JZKGBXrZzNPyg1IoTGPW0WGR4TdcPeGfPuto%3D



##az storage blob exists -c testcontainer -n sample.txt --account-name newstrac1 --connection-string "DefaultEndpointsProtocol=https;AccountName=newstrac1;AccountKey=$$$$$;EndpointSuffix=core.windows.net"

