# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Or Update Resource Group action on OC-DC'
      inputs:
        azureSubscription: MPN
        resourceGroupName: 'VirtualNetwork_01'
        location: 'West Europe'
        csmFile: 'Deploymentfiles/VirtualNetwork/AzureDeploy.json'
        csmParametersFile: 'Deploymentfiles/VirtualNetwork/AzureDeploy.parameters.json'
