# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go(b5e3024f-bc2c-4de4-8db0-bd025a10d518)'
    subscriptionId: 'b5e3024f-bc2c-4de4-8db0-bd025a10d518'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg2'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    deploymentMode: 'Incremental'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(b5e3024f-bc2c-4de4-8db0-bd025a10d518)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account set --subscription b5e3024f-bc2c-4de4-8db0-bd025a10d518
      az storage blob service-properties update --account-name testccount321 --static-website --404-document 404.html --index-document index.html
      ls
      pwd