# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'azcopy cp "https://strac1.blob.core.windows.net/testcontainer/testfile.txt?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-06-09T15:23:48Z&st=2022-06-09T07:23:48Z&spr=https&sig=BSfs2LQxDmeG2MvzAN9MwpPtBi2Jb5jflO9akNjvwjs%3D" "https://strac2.blob.core.windows.net/testcontainer/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-06-09T15:19:50Z&st=2022-06-09T07:19:50Z&spr=https&sig=ZQMjOCpUXjlQrQzZJF4dD9MTOn2vpfawp2bGvJIvR0M%3D" --recursive'