# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
- task: SSH@0
  inputs:
    sshEndpoint: 'new'
    runOptions: 'inline'
    inline: 'dfdf'
    readyTimeout: '20000'
variables:
- template: parameters.yml

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'new'
    runOptions: 'inline'
    inline: |
      touch file.txt
                   echo $(storage_account_name) >> file.txt
                   
                   while IFS=, read -ra arr; do
                    echo ${arr[0]}
                   done < file.txt
    readyTimeout: '20000'

- task: CmdLine@2
  displayName: 'Run a one-line script'
  inputs:
    script: |
       touch file.txt
       echo $(storage_account_name) >> file.txt
       
       while IFS=, read -ra arr; do
           echo ${arr[0]}
           echo ${arr[1]}
           echo ${arr[2]}
       done < file.txt
       #cut -d "," -f (field number) file.txt