# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
- template: parameters.yml

pool:
  vmImage: ubuntu-latest

steps:

- ${{ each value in ${{ variables.storage_account_name }} }}:
  - script: echo ${{ value }}

- script: 
     echo $(storage_account_name)
  displayName: 'Run a one-line script'