# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
- template: parameters.yml

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  displayName: 'Run a one-line script'
  inputs:
    script: |
      touch file.txt
      echo $(storage_account_name) >> file.txt
       ls -l
       cat file.txt